# Generated by Django 4.2 on 2024-06-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_subject_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(choices=[('Monday', 'Понеділок'), ('Tuesday', 'Вівторок'), ('Wednesday', 'Середа'), ('Thursday', 'Четвер'), ('Friday', "П'ятниця")], max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_schedule', to='base.group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_schedule', to='base.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('new_subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_subject', to='base.schedule')),
                ('old_subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='old_subject', to='base.schedule')),
            ],
        ),
    ]
