# Generated by Django 4.2 on 2024-06-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_schedule_replacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.DateTimeField(choices=[('Понеділок', 'Monday'), ('Вівторок', 'Tuesday'), ('Середа', 'Wednesday'), ('Четвер', 'Thursday'), ("П'ятниця", 'Friday')], max_length=15),
        ),
    ]
