# Generated by Django 4.2 on 2024-06-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_schedule_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='subject',
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ManyToManyField(related_name='subjects_schedule', to='base.subject'),
        ),
    ]
