# Generated by Django 4.2 on 2024-06-05 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_schedule_subject_schedule_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='replacement',
            name='new_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_subject', to='base.subject'),
        ),
        migrations.AlterField(
            model_name='replacement',
            name='old_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_subject', to='base.subject'),
        ),
    ]
