# Generated by Django 4.2 on 2024-06-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_schedule_end_time_remove_schedule_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.TimeField(default='12:40'),
            preserve_default=False,
        ),
    ]
