# Generated by Django 4.2 on 2024-06-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='audience',
            field=models.CharField(default='12:40', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='number_subject',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='subject',
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects_schedule', to='base.subject'),
            preserve_default=False,
        ),
    ]
